### PR TITLE
Issue 883

### PR DESCRIPTION
**Pull request by hegjon**
The current unit tests plays the receive-bitcoin sound

### CODE REVIEW

**Comment by hegjon** [comment]
I agree that the pull request code to be released under the MIT licence and does not contain any copyrighted material that I do not own.

**Comment by hegjon** [comment]
The client plays the receive-bitcoin sound when Play sound button is clicked (Preferences->Sounds)

**Comment by gary-rowe** [comment]
Thanks, Jonny!

**Comment by hegjon** [comment]
You are welcome

**Pull request merged**
